### ISSUE TITLE
MSL120 and bulb support

### ISSUE THREAD

**Issue by helenclarko** [vincenzosuraci/hassio_meross_sensor_switch#12]
I have two of these bulbs and I would love to know how I can help to get compatibility with Bulbs into this component.

Please let me know how I can help.

**Comment by vincenzosuraci** [comment]
Check if they works with the Meross iot library. I do not own such devices and lack of information to integrate them

**Comment by vincenzosuraci** [comment]
Dear all, I sugget to move on this component : [Alberto Geniola](https://github.com/albertogeniola/meross-homeassistant)
