### ISSUE TITLE
4 MSS310 switches. 1 works. 3 don't.

### ISSUE THREAD

**Issue by LuxMetrics** [vincenzosuraci/hassio_meross_sensor_switch#13]
I have home assistant, mosquitto and your code in containers on a Synology NAS. I have 4 mss310 switches and home assistant auto discovers them all.

All 4 work correctly as sensors. 1 also reads the status of the switch. It is also possible to switch it on and off from ha. The other 3 always show 'off'. Switching them on has no effect.

I notice that your log reads "[Device][_<switch name>_] Cannot read property 'channel' of undefined" each time I switch the problem switches on or off with the Meross app.

I find this quite puzzling. Have you any suggestions?

**Comment by vincenzosuraci** [comment]
Can you post the whole log?

**Comment by LuxMetrics** [comment]
Thanks for your speedy response! 
I also see the container crashed last night.
Aircon plug is the device that works. "Tumble Dryer", "Washing Machine" and "Air Purifier" do not. 
I turned 'Air Purifier' on and off from the Meross app at 02/07/2019  21:11:20.

[meross-carlosatta1.txt](https://github.com/vincenzosuraci/hassio_meross_sensor_switch/files/3353716/meross-carlosatta1.txt)

**Comment by LuxMetrics** [comment]
I think I have an answer. Although the plugs look the same 3 of them show hardware version 1.0.0 firmware  1.1.11 The working one is hardware version 2.0.0 firmware 2.1.9

**Comment by vincenzosuraci** [comment]
Dear all, I sugget to move on this component : [Alberto Geniola](https://github.com/albertogeniola/meross-homeassistant)
